const actions = {
  UPDATE_LIST_PRODUCT: 'UPDATE_LIST_PRODUCT',
  UPDATE_MYCARD: 'UPDATE_MYCARD',
  UPDATE_ORDER: 'UPDATE_ORDER',
  UPDATE_LINEORDER: 'UPDATE_LINEORDER',
  REMOVE_PRODUCT_IN_CART: 'REMOVE_PRODUCT_IN_CART',
};

export default actions;
